import { ShortLink, TrafficLog } from './types';

export const INITIAL_LINKS: ShortLink[] = [
  {
    id: 'link-1',
    slug: 'tech-deal-2026',
    title: 'Adsterra Smart Direct Offer (US/CA/UK)',
    targetUrl: 'https://www.highcpmgate.com/direct-sample-offer?campaign=fb_scale_q3',
    safePageType: 'tech-editorial',
    redirectMethod: 'meta-refresh',
    sensitivity: 'strict-fb',
    enabled: true,
    allowedCountries: ['US', 'CA', 'GB', 'AU'],
    allowedDevices: ['mobile', 'tablet'],
    requireFbclid: false,
    preserveUtms: true,
    notes: 'Main media buying test link for FB Newsfeed Carousel ads',
    createdAt: new Date(Date.now() - 3600 * 1000 * 48).toISOString(),
    health: {
      score: 98,
      riskLevel: 'safe',
      crawlerScanSurge: false,
      metaReviewFrequency: 'normal',
      lastCrawlerAudit: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      recommendation: '🟢 100% Policy Shielded. 135 review bots safely isolated, 1,285 real buyers forwarded.',
    },
    clicks: {
      total: 1420,
      human: 1285,
      bot: 135,
    },
  },
  {
    id: 'link-2',
    slug: 'gadget-reviews',
    title: 'Smart Gadget Sales Funnel & Bundle',
    targetUrl: 'https://smartgadgetshub.store/checkout-bundle-v2',
    safePageType: 'ecommerce-showcase',
    redirectMethod: 'js-instant',
    sensitivity: 'strict-fb',
    enabled: true,
    allowedCountries: [],
    allowedDevices: ['mobile', 'desktop', 'tablet'],
    requireFbclid: true,
    preserveUtms: true,
    notes: 'Direct to sales funnel - requiring fbclid parameter',
    createdAt: new Date(Date.now() - 3600 * 1000 * 24).toISOString(),
    health: {
      score: 95,
      riskLevel: 'safe',
      crawlerScanSurge: false,
      metaReviewFrequency: 'normal',
      lastCrawlerAudit: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      recommendation: '🟢 Optimal Health. FBCLID verification active. Zero leaks detected.',
    },
    clicks: {
      total: 890,
      human: 812,
      bot: 78,
    },
  },
  {
    id: 'link-3',
    slug: 'growth-strategy',
    title: 'B2B Agency Lead Magnet & Consult',
    targetUrl: 'https://agencygrowthpro.io/vip-webinar-apply',
    safePageType: 'agency-services',
    redirectMethod: 'meta-refresh',
    sensitivity: 'standard',
    enabled: true,
    allowedCountries: ['US', 'UK', 'SG', 'AE'],
    allowedDevices: ['desktop', 'mobile'],
    requireFbclid: false,
    preserveUtms: true,
    notes: 'Safe bridge page with instant stealth forwarding for real buyers',
    createdAt: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
    health: {
      score: 91,
      riskLevel: 'low-risk',
      crawlerScanSurge: false,
      metaReviewFrequency: 'elevated',
      lastCrawlerAudit: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
      recommendation: '🛡️ Minor Meta health probe detected. Corporate White Page served.',
    },
    clicks: {
      total: 415,
      human: 380,
      bot: 35,
    },
  },
];

export const INITIAL_LOGS: TrafficLog[] = [
  {
    id: 'log-1',
    linkId: 'link-1',
    slug: 'tech-deal-2026',
    timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    ip: '173.252.87.12',
    country: 'US',
    device: 'bot',
    browser: 'Unknown Browser',
    os: 'Linux',
    referrer: 'https://l.facebook.com/',
    userAgent: 'facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)',
    isBot: true,
    detectionReasons: ['Meta Review Crawler (facebookexternalhit)'],
    actionTaken: 'served-safe-page',
    urlParams: { fbclid: 'IwAR1sampleBotCheck' },
  },
  {
    id: 'log-2',
    linkId: 'link-1',
    slug: 'tech-deal-2026',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    ip: '98.142.112.44',
    country: 'US',
    device: 'mobile',
    browser: 'Facebook Mobile In-App Browser',
    os: 'iOS (Apple)',
    referrer: 'http://m.facebook.com',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone15,2;FBMD/iPhone;FBSN/iOS;FBSV/17.4;FBSS/3;FBCR/Verizon;FBID/phone;FBLC/en_US;FBOP/5]',
    isBot: false,
    detectionReasons: [],
    actionTaken: 'redirected-to-target',
    urlParams: { utm_source: 'fb_ads', utm_campaign: 'q3_scale', fbclid: 'IwAR3RealAdClickUser_987654' },
  },
  {
    id: 'log-3',
    linkId: 'link-2',
    slug: 'gadget-reviews',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    ip: '66.220.149.25',
    country: 'US',
    device: 'bot',
    browser: 'Unknown Browser',
    os: 'Linux',
    referrer: '',
    userAgent: 'Facebot/1.0',
    isBot: true,
    detectionReasons: ['Meta Review Crawler (facebot)', 'Missing Accept-Language header'],
    actionTaken: 'served-safe-page',
    urlParams: {},
  },
  {
    id: 'log-4',
    linkId: 'link-2',
    slug: 'gadget-reviews',
    timestamp: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    ip: '104.28.19.88',
    country: 'GB',
    device: 'mobile',
    browser: 'Apple Safari',
    os: 'iOS (Apple)',
    referrer: 'https://l.facebook.com/',
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1',
    isBot: false,
    detectionReasons: [],
    actionTaken: 'redirected-to-target',
    urlParams: { utm_medium: 'cpc', fbclid: 'IwAR8ValidAdTrafficGB_123' },
  },
  {
    id: 'log-5',
    linkId: 'link-3',
    slug: 'growth-strategy',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    ip: '34.221.90.14',
    country: 'US',
    device: 'bot',
    browser: 'Google Chrome',
    os: 'Linux',
    referrer: '',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/124.0.6367.60 Safari/537.36',
    isBot: true,
    detectionReasons: ['Automated Headless / Review Engine (headlesschrome)'],
    actionTaken: 'served-safe-page',
    urlParams: {},
  },
];
